spring:
  redis:
   port: 6379
   host: localhost
  jpa:
    hibernate:
      ddl-auto: update
value:
  rendered: SecondchangedStaging
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
ds:
  url: jdbc:mysql://localhost:3306/devDB