spring:
  jpa:
    hibernate:
      ddl-auto: update
value:
  rendered: SecondchangedStaging
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
ds:
  url: jdbc:mysql://host.docker.internal:3306/testDB